### PR TITLE
Fix crash with empty motion names. Fixes #20.

### LINKED ISSUE #20: Program crashes with empty motion name
The problem was introduced in the refactoring of `play_motion.cpp` into `play_motion_helpers.cpp`

We should get a `NodeHandle` namespaced to `play_motion/motions` and check `nh_motions.hasParam(motion_id)`

### PR DESCRIPTION
**Pull request by adolfo-rt**

### CODE REVIEW

File: play_motion/include/play_motion/play_motion_helpers.h [hunk 1]
```diff
@@ -93,7 +93,12 @@
    */
   void getMotionIds(const ros::NodeHandle &nh, MotionNames& motion_ids);
 
-
+  /**
+   * @param nh Nodehandle with the namespace containing the motions
```
Comment (po1) [inline play_motion/include/play_motion/play_motion_helpers.h:97]: Huh, seems like we have an inconsistency. I have used backquote doxygen `\param` in some other files...

File: play_motion/src/play_motion_helpers.cpp [hunk 2]
```diff
@@ -215,9 +222,15 @@
   void getMotion(const ros::NodeHandle &nh, const std::string &motion_id,
                  MotionInfo &motionInfo)
   {
+    if (!motionExists(nh, motion_id))
+    {
+      const std::string what = "Motion '" + motion_id + "' does not exist or is malformed " +
+                               "(namespace " + getMotionsNodeHandle(nh).getNamespace() + ").";
+      throw xh::XmlrpcHelperException(what);
```
Comment (po1) [inline play_motion/src/play_motion_helpers.cpp]: Why throw an `xh::XmlrpcHelperException`?

Comment (adolfo-rt) [inline play_motion/src/play_motion_helpers.cpp]: You mean instead of some other exception type?. Because no additional catch logic needed to be written in play motion code, which now that I check, is only two places.

Proposal: How about moving `PMException` to `play_motion/datatypes.h` and throwing that?, plus adding two more catch statements for this type.

File: play_motion/include/play_motion/play_motion_helpers.h (hunk 1 above)
Comment (adolfo-rt) [inline play_motion/include/play_motion/play_motion_helpers.h:97]: I was just being consistent with the rest of the file. How about merging this PR, and then do tag harmonizing, which goes beyond the scope of this PR?.

File: play_motion/src/play_motion_helpers.cpp (hunk 2 above)
Comment (adolfo-rt) [inline play_motion/src/play_motion_helpers.cpp]: So moving `PMException` is not a good idea, as it depends on `play_motion_msgs`. I went for throwing a `ros::Exception`, which is the type thrown by the other functions in the file.

File: play_motion/src/play_motion_helpers.cpp [hunk 3]
```diff
@@ -215,9 +222,15 @@
   void getMotion(const ros::NodeHandle &nh, const std::string &motion_id,
                  MotionInfo &motionInfo)
   {
+    if (!motionExists(nh, motion_id))
+    {
+      const std::string what = "Motion '" + motion_id + "' does not exist or is malformed " +
+                               "(namespace " + getMotionsNodeHandle(nh).getNamespace() + ").";
+      throw ros::Exception(what);
```
Comment (adolfo-rt) [inline play_motion/src/play_motion_helpers.cpp:229]: Throwing `ros::Exception` now.

Comment (po1) [inline play_motion/src/play_motion_helpers.cpp:229]: I'm rather good with that. When we really want to separate it from other ROS exceptions, we can still make up our own.

File: play_motion/include/play_motion/play_motion_helpers.h (hunk 1 above)
Comment (po1) [inline play_motion/include/play_motion/play_motion_helpers.h:97]: No problem. I was using this to highlight a fact, not to display my disapproval. The PR itself is fine.

File: play_motion/include/play_motion/play_motion_helpers.h [hunk 4]
```diff
@@ -148,6 +153,13 @@
    */
   void populateVelocities(const Trajectory& traj_in, Trajectory& traj_out);
 
+  /**
+   * @brief Parse a motion specified in the ROS parameter server into a data structure.
+   * @param[in] nh Nodehandle with the namespace containing the motions
+   *           (ie ros::NodeHandle nh("play_motion"))
+   * @param[in] motion_id Motion identifier
+   * @param[out] motionInfo Data structure containing parsed motion
```
Comment (po1) [inline play_motion/include/play_motion/play_motion_helpers.h:161]: Should we mention something like `@throws ros::Exception` here?

Comment (adolfo-rt) [inline play_motion/include/play_motion/play_motion_helpers.h:161]: Definitely yes. Done, see below.

File: play_motion/test/play_motion_helpers_test.cpp [hunk 5]
```diff
@@ -33,6 +33,7 @@
 #include <ros/time.h>
 
 #include "play_motion/play_motion_helpers.h"
+#include "play_motion/xmlrpc_helpers.h"
```
Comment (po1) [inline play_motion/test/play_motion_helpers_test.cpp]: Is this include still needed?

**Comment by adolfo-rt** [comment]
Hopefully all concerns are now addressed.

**Comment by po1** [comment]
Perfect, merging. Thanks!
